/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";
import type * as ai from "../../ai/index.js";
import type * as baml from "../../baml/index.js";

/**
 * Provider-neutral media payload after resolving local files and, when
 * requested, ordinary HTTP(S) URLs. Google Cloud `gs://` URLs remain URLs.
 */
export class ResolvedMedia$stream {
  url!: string | null;
  base64!: string | null;
  mime_type!: string | null;
  constructor(init: {
    url: string | null;
    base64: string | null;
    mime_type: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * `send_as_with_wire`'s result: the decoded envelope plus the wire record.
 */
export class SentAs$stream<T> {
  value!: T | null;
  call!: ai.events.LLMCall$stream | null;
  $types?: { T?: BamlType | BamlTypeToken };
  constructor(init: {
    value: T | null;
    call: ai.events.LLMCall$stream | null;
    $types?: { T?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T"] as const;
}

/**
 * Collapse a client's `root.Credential?` option to the value to put on the
 * wire, reading the environment at REQUEST time (never at construction).
 * 
 *   * a literal string resolves to itself, unless it is blank — a
 *     whitespace-only credential is treated as "not configured" so the rest of
 *     the chain can supply one;
 *   * a `baml.env.Ref` resolves to `ref.get()` — `null` when the named
 *     variable is unset, which lets the caller continue down its own chain (or
 *     raise the same error it raises for an unconfigured option);
 *   * `null` falls back to `env_fallback`, the provider's canonical variable
 *     name, looked up with `baml.env.get`. A `null` `env_fallback` means the
 *     provider has no canonical variable and the result is `null`.
 * 
 * A BLANK value is "not configured" at EVERY rung, not just the literal one:
 * `export OPENAI_API_KEY=` otherwise resolved to `""` and every client built
 * `Authorization: Bearer ` — a provider 401 in place of the local "no
 * credential configured" error the same client raises when the variable is
 * absent entirely. The two spellings of "I did not set this" now behave alike.
 * 
 * This IS the whole chain a client needs: explicit credential (a literal or an
 * `env.NAME` ref) → the provider's canonical variable (`env_fallback`).
 * @throws Io
 * @throws ParseError
 */
export const resolve_credential = defineFunction("ai.wire.resolve_credential", "sync", ["cred", "env_fallback"]) as (cred: ai.Credential | null, env_fallback: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;

/**
 * Collapse a client's `root.Credential?` option to the value to put on the
 * wire, reading the environment at REQUEST time (never at construction).
 * 
 *   * a literal string resolves to itself, unless it is blank — a
 *     whitespace-only credential is treated as "not configured" so the rest of
 *     the chain can supply one;
 *   * a `baml.env.Ref` resolves to `ref.get()` — `null` when the named
 *     variable is unset, which lets the caller continue down its own chain (or
 *     raise the same error it raises for an unconfigured option);
 *   * `null` falls back to `env_fallback`, the provider's canonical variable
 *     name, looked up with `baml.env.get`. A `null` `env_fallback` means the
 *     provider has no canonical variable and the result is `null`.
 * 
 * A BLANK value is "not configured" at EVERY rung, not just the literal one:
 * `export OPENAI_API_KEY=` otherwise resolved to `""` and every client built
 * `Authorization: Bearer ` — a provider 401 in place of the local "no
 * credential configured" error the same client raises when the variable is
 * absent entirely. The two spellings of "I did not set this" now behave alike.
 * 
 * This IS the whole chain a client needs: explicit credential (a literal or an
 * `env.NAME` ref) → the provider's canonical variable (`env_fallback`).
 * @throws Io
 * @throws ParseError
 */
export const resolve_credential_async = defineFunction("ai.wire.resolve_credential", "async", ["cred", "env_fallback"]) as (cred: ai.Credential | null, env_fallback: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;

/**
 * Scrub credential-bearing query parameters out of free text before it becomes
 * an `ai.errors.Failure.detail`.
 * 
 * Providers that authenticate through the URL — Vertex AI express mode puts
 * the key in `?key=…` — would otherwise leak it: the native HTTP layer renders
 * `reqwest::Error`, whose `Display` embeds the request URL, straight into the
 * transport-failure message.
 */
export const redact_url_secrets = defineFunction("ai.wire.redact_url_secrets", "sync", ["text"]) as (text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * Scrub credential-bearing query parameters out of free text before it becomes
 * an `ai.errors.Failure.detail`.
 * 
 * Providers that authenticate through the URL — Vertex AI express mode puts
 * the key in `?key=…` — would otherwise leak it: the native HTTP layer renders
 * `reqwest::Error`, whose `Display` embeds the request URL, straight into the
 * transport-failure message.
 */
export const redact_url_secrets_async = defineFunction("ai.wire.redact_url_secrets", "async", ["text"]) as (text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * Replace credential-bearing request headers with "REDACTED" before a
 * request snapshot rides an `ai.events.LLMCall`. Unlike previews, the
 * request `invoke` actually sends DOES carry auth headers (`x-api-key`,
 * `authorization`, Azure's `api-key`, ...), so captured requests must be
 * scrubbed. Matching is case-insensitive; values are replaced, names kept.
 */
export const redact_request_headers = defineFunction("ai.wire.redact_request_headers", "sync", ["headers"]) as (headers: { [key: string]: string }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => { [key: string]: string };

/**
 * Replace credential-bearing request headers with "REDACTED" before a
 * request snapshot rides an `ai.events.LLMCall`. Unlike previews, the
 * request `invoke` actually sends DOES carry auth headers (`x-api-key`,
 * `authorization`, Azure's `api-key`, ...), so captured requests must be
 * scrubbed. Matching is case-insensitive; values are replaced, names kept.
 */
export const redact_request_headers_async = defineFunction("ai.wire.redact_request_headers", "async", ["headers"]) as (headers: { [key: string]: string }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<{ [key: string]: string }>;

/**
 * The environment variables a credential chain consulted, as a readable list,
 * for the "no credential configured" error a client raises when the whole
 * chain came back empty.
 * 
 * The point is the `Ref` arm: `api_key = env.MY_KEY` pointing at an UNSET
 * variable resolves to `null` and falls through to the rest of the chain, so
 * without this the error would name only the provider's canonical variable and
 * never mention the one the caller actually asked for. Values are never
 * included — only names.
 */
export const credential_sources = defineFunction("ai.wire.credential_sources", "sync", ["cred", "canonical_env"]) as (cred: ai.Credential | null, canonical_env: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * The environment variables a credential chain consulted, as a readable list,
 * for the "no credential configured" error a client raises when the whole
 * chain came back empty.
 * 
 * The point is the `Ref` arm: `api_key = env.MY_KEY` pointing at an UNSET
 * variable resolves to `null` and falls through to the rest of the chain, so
 * without this the error would name only the provider's canonical variable and
 * never mention the one the caller actually asked for. Values are never
 * included — only names.
 */
export const credential_sources_async = defineFunction("ai.wire.credential_sources", "async", ["cred", "canonical_env"]) as (cred: ai.Credential | null, canonical_env: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * @throws Timeout
 */
export const send_as = defineFunction("ai.wire.send_as", "sync", ["req", "provider"], ["request_timeout_ms"], { typeParams: ["T"] }) as <T>(req: baml.http.Request, provider: string, $opts?: { request_timeout_ms?: number | null | undefined; $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;

/**
 * @throws Timeout
 */
export const send_as_async = defineFunction("ai.wire.send_as", "async", ["req", "provider"], ["request_timeout_ms"], { typeParams: ["T"] }) as <T>(req: baml.http.Request, provider: string, $opts?: { request_timeout_ms?: number | null | undefined; $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;

/**
 * `send_as_with_wire`'s result: the decoded envelope plus the wire record.
 */
export class SentAs<T> {
  value!: T;
  call!: ai.events.LLMCall;
  $types?: { T?: BamlType | BamlTypeToken };
  constructor(init: {
    value: T;
    call: ai.events.LLMCall;
    $types?: { T?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T"] as const;
}

/**
 * Same contract as `send_as`, plus the LLMCall wire record. On a non-2xx or
 * transport failure this still throws the same classified error `send_as`
 * throws — composite clients build failed-leg records from the error itself
 * (`_failed_leg_call`), so no record accompanies a throw. `capture_wire`
 * gates the request/response bodies; status, headers, and timing are always
 * recorded. The request URL and captured response body are redacted with
 * `redact_url_secrets` before storing.
 * @throws Timeout
 */
export const send_as_with_wire = defineFunction("ai.wire.send_as_with_wire", "sync", ["req", "provider", "client_name"], ["capture_wire", "request_timeout_ms"], { typeParams: ["T"] }) as <T>(req: baml.http.Request, provider: string, client_name: string, $opts?: { capture_wire?: boolean | undefined; request_timeout_ms?: number | null | undefined; $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => SentAs<T>;

/**
 * Same contract as `send_as`, plus the LLMCall wire record. On a non-2xx or
 * transport failure this still throws the same classified error `send_as`
 * throws — composite clients build failed-leg records from the error itself
 * (`_failed_leg_call`), so no record accompanies a throw. `capture_wire`
 * gates the request/response bodies; status, headers, and timing are always
 * recorded. The request URL and captured response body are redacted with
 * `redact_url_secrets` before storing.
 * @throws Timeout
 */
export const send_as_with_wire_async = defineFunction("ai.wire.send_as_with_wire", "async", ["req", "provider", "client_name"], ["capture_wire", "request_timeout_ms"], { typeParams: ["T"] }) as <T>(req: baml.http.Request, provider: string, client_name: string, $opts?: { capture_wire?: boolean | undefined; request_timeout_ms?: number | null | undefined; $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<SentAs<T>>;

/**
 * @throws CompilationError
 */
export const render_output_format = defineFunction("ai.wire.render_output_format", "sync", ["t"]) as (t: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * @throws CompilationError
 */
export const render_output_format_async = defineFunction("ai.wire.render_output_format", "async", ["t"]) as (t: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * Provider-neutral media payload after resolving local files and, when
 * requested, ordinary HTTP(S) URLs. Google Cloud `gs://` URLs remain URLs.
 */
export class ResolvedMedia {
  url!: string | null;
  base64!: string | null;
  mime_type!: string;
  constructor(init: {
    url: string | null;
    base64: string | null;
    mime_type: string;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Resolve BAML media for provider request lowering. This mirrors the media
 * resolution pass in `sys_llm`: local files become base64, existing base64 is
 * retained, and URL fetching is selected by the provider.
 * @throws NetworkFailure
 * @throws InvalidArgument
 * @throws Io
 * @throws Timeout
 */
export const resolve_media = defineFunction("ai.wire.resolve_media", "sync", ["media", "fetch_url"]) as (media: ai.MediaPart, fetch_url: boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ResolvedMedia;

/**
 * Resolve BAML media for provider request lowering. This mirrors the media
 * resolution pass in `sys_llm`: local files become base64, existing base64 is
 * retained, and URL fetching is selected by the provider.
 * @throws NetworkFailure
 * @throws InvalidArgument
 * @throws Io
 * @throws Timeout
 */
export const resolve_media_async = defineFunction("ai.wire.resolve_media", "async", ["media", "fetch_url"]) as (media: ai.MediaPart, fetch_url: boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ResolvedMedia>;

/**
 * Resolve media for a request preview without reading a file or fetching a
 * URL. Existing base64 and `data:` payloads are preserved; provider-specific
 * renderers decide whether an ordinary URL is supported on their wire form.
 * @throws PreviewUnsupported
 */
export const resolve_media_preview = defineFunction("ai.wire.resolve_media_preview", "sync", ["media"]) as (media: ai.MediaPart, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ResolvedMedia;

/**
 * Resolve media for a request preview without reading a file or fetching a
 * URL. Existing base64 and `data:` payloads are preserved; provider-specific
 * renderers decide whether an ordinary URL is supported on their wire form.
 * @throws PreviewUnsupported
 */
export const resolve_media_preview_async = defineFunction("ai.wire.resolve_media_preview", "async", ["media"]) as (media: ai.MediaPart, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ResolvedMedia>;

/**
 * Deep-merge a client's `request_body` passthrough into its serialized
 * request. Call this as the LAST step of building the wire body:
 * 
 *     let body = baml.json.to_json(typed_request);
 *     let merged = ai.wire.merge_request_body(body, c.request_body);
 *     baml.json.stringify(merged)
 * 
 * Maps merge recursively, a `null` override value DELETES that key (the
 * engine's removal contract — `{"max_tokens": null}` removes the default the
 * client injected), and every other value replaces wholesale. A `null`
 * `overrides` means "no passthrough configured" and returns `base` unchanged;
 * it never deletes the whole body.
 */
export const merge_request_body = defineFunction("ai.wire.merge_request_body", "sync", ["base", "overrides"]) as (base: baml.json.json, overrides: baml.json.json | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.json.json;

/**
 * Deep-merge a client's `request_body` passthrough into its serialized
 * request. Call this as the LAST step of building the wire body:
 * 
 *     let body = baml.json.to_json(typed_request);
 *     let merged = ai.wire.merge_request_body(body, c.request_body);
 *     baml.json.stringify(merged)
 * 
 * Maps merge recursively, a `null` override value DELETES that key (the
 * engine's removal contract — `{"max_tokens": null}` removes the default the
 * client injected), and every other value replaces wholesale. A `null`
 * `overrides` means "no passthrough configured" and returns `base` unchanged;
 * it never deletes the whole body.
 */
export const merge_request_body_async = defineFunction("ai.wire.merge_request_body", "async", ["base", "overrides"]) as (base: baml.json.json, overrides: baml.json.json | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.json.json>;

/**
 * Make one run's journal safe to replay to `client_id`, and return the
 * sanitized copy. Every client should lower
 * `ai.wire.sanitize_for_client(input.journal, self.id())` instead of
 * `input.journal`. The rules, in the order they apply per event:
 * 
 *  1. An assistant turn from a DIFFERENT `client_id` loses its
 *     `ai.content.Reasoning` blocks: one model's thinking is not replayable
 *     to another (and providers that check reasoning signatures reject it).
 *  2. Empty and whitespace-only `ai.content.Text` blocks are dropped from
 *     assistant turns.
 *  3. An assistant turn left with no blocks at all is dropped entirely —
 *     the reasoning-only turn that lowers to `content: []` and makes
 *     Anthropic 400, and the same shape an aborted turn leaves behind.
 *     Such a turn never has tool calls, so nothing is orphaned by dropping it.
 *  4. A tool call with no `ToolCompleted`/`ToolFailed` before the next
 *     assistant or user message (or before the end of the journal) gets a
 *     synthesized `ToolFailed { message: "No result provided" }`, because
 *     most APIs reject a tool call that was never answered.
 * 
 * Journal-only events (`RunStarted`, `ToolRequested`, `Usage`,
 * `FinalProduced`) pass through untouched — clients skip them anyway — and,
 * like the clients' own lowering, they never close an open tool-result group.
 * Nothing here mutates the journal it is given.
 */
export const sanitize_for_client = defineFunction("ai.wire.sanitize_for_client", "sync", ["j", "client_id"]) as (j: ai.Journal, client_id: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.Journal;

/**
 * Make one run's journal safe to replay to `client_id`, and return the
 * sanitized copy. Every client should lower
 * `ai.wire.sanitize_for_client(input.journal, self.id())` instead of
 * `input.journal`. The rules, in the order they apply per event:
 * 
 *  1. An assistant turn from a DIFFERENT `client_id` loses its
 *     `ai.content.Reasoning` blocks: one model's thinking is not replayable
 *     to another (and providers that check reasoning signatures reject it).
 *  2. Empty and whitespace-only `ai.content.Text` blocks are dropped from
 *     assistant turns.
 *  3. An assistant turn left with no blocks at all is dropped entirely —
 *     the reasoning-only turn that lowers to `content: []` and makes
 *     Anthropic 400, and the same shape an aborted turn leaves behind.
 *     Such a turn never has tool calls, so nothing is orphaned by dropping it.
 *  4. A tool call with no `ToolCompleted`/`ToolFailed` before the next
 *     assistant or user message (or before the end of the journal) gets a
 *     synthesized `ToolFailed { message: "No result provided" }`, because
 *     most APIs reject a tool call that was never answered.
 * 
 * Journal-only events (`RunStarted`, `ToolRequested`, `Usage`,
 * `FinalProduced`) pass through untouched — clients skip them anyway — and,
 * like the clients' own lowering, they never close an open tool-result group.
 * Nothing here mutates the journal it is given.
 */
export const sanitize_for_client_async = defineFunction("ai.wire.sanitize_for_client", "async", ["j", "client_id"]) as (j: ai.Journal, client_id: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.Journal>;
