/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, initializeRuntimeFromBytecode, setTypeMap, type BamlCallContext, type BamlType } from "@boundaryml/baml-bridge";
import * as _inlinedbaml from "./_inlinedbaml.js";
import { _TYPE_MAP } from "./_typemap.js";
import type * as ai from "./ai/index.js";
import type * as baml from "./baml/index.js";

initializeRuntimeFromBytecode(_inlinedbaml.BYTECODE, _inlinedbaml.BAML_TOML);
setTypeMap(_TYPE_MAP);

export * as ai from "./ai/index.js";
export * as baml from "./baml/index.js";
export * as reflect from "./reflect/index.js";
export * as vendor from "./vendor/index.js";

export class Contact$stream {
  name!: string | null;
  email!: string | null;
  phone!: string | null;
  tags!: string[];
  constructor(init: {
    name: string | null;
    email: string | null;
    phone: string | null;
    tags: string[];
  }) {
    Object.assign(this, init);
  }
}

export class DivisionByZeroError$stream {
  message!: string | null;
  constructor(init: {
    message: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class InvalidEmailError$stream {
  email!: string | null;
  message!: string | null;
  constructor(init: {
    email: string | null;
    message: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class Summary$stream {
  headline!: string | null;
  bullets!: string[];
  constructor(init: {
    headline: string | null;
    bullets: string[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Reverses the characters in `text`.
 */
export const ReverseText = defineFunction("user.ReverseText", "sync", ["text"]) as (text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * Reverses the characters in `text`.
 */
export const ReverseText_async = defineFunction("user.ReverseText", "async", ["text"]) as (text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * Title-cases every word in `text`.
 */
export const TitleCase = defineFunction("user.TitleCase", "sync", ["text"]) as (text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * Title-cases every word in `text`.
 */
export const TitleCase_async = defineFunction("user.TitleCase", "async", ["text"]) as (text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * Counts how many times each word appears in `text` (case-insensitive).
 */
export const WordFrequency = defineFunction("user.WordFrequency", "sync", ["text"]) as (text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => { [key: string]: number };

/**
 * Counts how many times each word appears in `text` (case-insensitive).
 */
export const WordFrequency_async = defineFunction("user.WordFrequency", "async", ["text"]) as (text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<{ [key: string]: number }>;

export class DivisionByZeroError {
  message!: string;
  constructor(init: {
    message: string;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Divides two numbers, rejecting division by zero.
 * @throws DivisionByZeroError
 */
export const Divide = defineFunction("user.Divide", "sync", ["numerator", "denominator"]) as (numerator: number, denominator: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => number;

/**
 * Divides two numbers, rejecting division by zero.
 * @throws DivisionByZeroError
 */
export const Divide_async = defineFunction("user.Divide", "async", ["numerator", "denominator"]) as (numerator: number, denominator: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<number>;

export class Contact {
  name!: string;
  email!: string;
  phone!: string | null;
  tags!: string[];
  constructor(init: {
    name: string;
    email: string;
    phone: string | null;
    tags: string[];
  }) {
    Object.assign(this, init);
  }
}

export class InvalidEmailError {
  email!: string;
  message!: string;
  constructor(init: {
    email: string;
    message: string;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Builds a normalized contact record, validating the email shape.
 * @throws InvalidEmailError
 */
export const BuildContact = defineFunction("user.BuildContact", "sync", ["name", "email"], ["phone", "tags"]) as (name: string, email: string, $opts?: { phone?: string | null | undefined; tags?: string[] | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Contact;

/**
 * Builds a normalized contact record, validating the email shape.
 * @throws InvalidEmailError
 */
export const BuildContact_async = defineFunction("user.BuildContact", "async", ["name", "email"], ["phone", "tags"]) as (name: string, email: string, $opts?: { phone?: string | null | undefined; tags?: string[] | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Contact>;

export enum Tone {
  Neutral = "Neutral",
  Enthusiastic = "Enthusiastic",
  Formal = "Formal",
}

export class Summary {
  headline!: string;
  bullets!: string[];
  constructor(init: {
    headline: string;
    bullets: string[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Summarizes `text` into a headline and a few bullets, in the requested tone.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const SummarizeText = defineFunction("user.SummarizeText", "sync", ["text", "tone"]) as (text: string, tone: Tone, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Summary;

/**
 * Summarizes `text` into a headline and a few bullets, in the requested tone.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const SummarizeText_async = defineFunction("user.SummarizeText", "async", ["text", "tone"]) as (text: string, tone: Tone, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Summary>;

/**
 * Summarizes `text` into a headline and a few bullets, in the requested tone.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const SummarizeText$build_request = defineFunction("user.SummarizeText$build_request", "sync", ["text", "tone"]) as (text: string, tone: Tone, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.http.Request;

/**
 * Summarizes `text` into a headline and a few bullets, in the requested tone.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const SummarizeText$build_request_async = defineFunction("user.SummarizeText$build_request", "async", ["text", "tone"]) as (text: string, tone: Tone, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * Summarizes `text` into a headline and a few bullets, in the requested tone.
 * @throws LlmClient
 */
export const SummarizeText$parse = defineFunction("user.SummarizeText$parse", "sync", ["json"]) as (json: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Summary;

/**
 * Summarizes `text` into a headline and a few bullets, in the requested tone.
 * @throws LlmClient
 */
export const SummarizeText$parse_async = defineFunction("user.SummarizeText$parse", "async", ["json"]) as (json: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Summary>;

/**
 * Summarizes `text` into a headline and a few bullets, in the requested tone.
 * @throws InvalidArgument
 * @throws CompilationError
 */
export const SummarizeText$render_prompt = defineFunction("user.SummarizeText$render_prompt", "sync", ["text", "tone"]) as (text: string, tone: Tone, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.Prompt;

/**
 * Summarizes `text` into a headline and a few bullets, in the requested tone.
 * @throws InvalidArgument
 * @throws CompilationError
 */
export const SummarizeText$render_prompt_async = defineFunction("user.SummarizeText$render_prompt", "async", ["text", "tone"]) as (text: string, tone: Tone, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.Prompt>;

/**
 * Summarizes `text` into a headline and a few bullets, in the requested tone.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const SummarizeText$stream = defineFunction("user.SummarizeText$stream", "sync", ["text", "tone"]) as (text: string, tone: Tone, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.stream.Stream<Summary$stream | null, Summary>;

/**
 * Summarizes `text` into a headline and a few bullets, in the requested tone.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const SummarizeText$stream_async = defineFunction("user.SummarizeText$stream", "async", ["text", "tone"]) as (text: string, tone: Tone, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.stream.Stream<Summary$stream | null, Summary>>;

/**
 * One function of this package, shaped for an auto-generated console card.
 *
 * Attributes:
 *   name
 *   docstring
 *   params
 *   returns_type_name
 *   returns_json_schema
 *   throws_type_name: "never" if the function cannot throw.
 */
export class FunctionInfo$stream {
  name!: string | null;
  docstring!: string | null;
  params!: ParamInfo$stream[];
  returns_type_name!: string | null;
  returns_json_schema!: string | null;
  throws_type_name!: string | null;
  constructor(init: {
    name: string | null;
    docstring: string | null;
    params: ParamInfo$stream[];
    returns_type_name: string | null;
    returns_json_schema: string | null;
    throws_type_name: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * The result of a reflective invocation: exactly one of `value` (success)
 * or `error_type` + `error_message` (failure) is populated.
 */
export class InvokeResult$stream {
  ok!: boolean | null;
  value!: unknown | null;
  error_type!: string | null;
  error_message!: string | null;
  constructor(init: {
    ok: boolean | null;
    value: unknown | null;
    error_type: string | null;
    error_message: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * One parameter of a reflected function, shaped for an auto-generated form.
 *
 * Attributes:
 *   name
 *   type_name
 *   json_schema: JSON Schema for this parameter's type (`baml.json.schema`), as a JSON
 *     string — the frontend picks a form control from its `"type"`.
 *   required
 */
export class ParamInfo$stream {
  name!: string | null;
  type_name!: string | null;
  json_schema!: string | null;
  required!: boolean | null;
  constructor(init: {
    name: string | null;
    type_name: string | null;
    json_schema: string | null;
    required: boolean | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * One parameter of a reflected function, shaped for an auto-generated form.
 *
 * Attributes:
 *   name
 *   type_name
 *   json_schema: JSON Schema for this parameter's type (`baml.json.schema`), as a JSON
 *     string — the frontend picks a form control from its `"type"`.
 *   required
 */
export class ParamInfo {
  name!: string;
  type_name!: string;
  json_schema!: string;
  required!: boolean;
  constructor(init: {
    name: string;
    type_name: string;
    json_schema: string;
    required: boolean;
  }) {
    Object.assign(this, init);
  }
}

/**
 * One function of this package, shaped for an auto-generated console card.
 *
 * Attributes:
 *   name
 *   docstring
 *   params
 *   returns_type_name
 *   returns_json_schema
 *   throws_type_name: "never" if the function cannot throw.
 */
export class FunctionInfo {
  name!: string;
  docstring!: string | null;
  params!: ParamInfo[];
  returns_type_name!: string;
  returns_json_schema!: string;
  throws_type_name!: string;
  constructor(init: {
    name: string;
    docstring: string | null;
    params: ParamInfo[];
    returns_type_name: string;
    returns_json_schema: string;
    throws_type_name: string;
  }) {
    Object.assign(this, init);
  }
}

export const _param_info = defineFunction("user._param_info", "sync", ["name", "t", "required"]) as (name: string, t: BamlType, required: boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ParamInfo;

export const _param_info_async = defineFunction("user._param_info", "async", ["name", "t", "required"]) as (name: string, t: BamlType, required: boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ParamInfo>;

/**
 * True for functions that are part of the reflection plumbing itself (this
 * file, by its `_`-prefixed local names) or compiler-synthesized companions
 * ($parse, $render_prompt, $spec, $stream) — neither belongs in the console.
 */
export const _is_internal = defineFunction("user._is_internal", "sync", ["name"]) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => boolean;

/**
 * True for functions that are part of the reflection plumbing itself (this
 * file, by its `_`-prefixed local names) or compiler-synthesized companions
 * ($parse, $render_prompt, $spec, $stream) — neither belongs in the console.
 */
export const _is_internal_async = defineFunction("user._is_internal", "async", ["name"]) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<boolean>;

/**
 * Enumerates every invocable function in this package via
 * `reflect.Package.current()` + `reflect.signature()`. Add a function to
 * functions.baml and, on restart, it appears here — nothing changes here.
 * @throws CompilationError
 */
export const ListFunctions = defineFunction("user.ListFunctions", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => FunctionInfo[];

/**
 * Enumerates every invocable function in this package via
 * `reflect.Package.current()` + `reflect.signature()`. Add a function to
 * functions.baml and, on restart, it appears here — nothing changes here.
 * @throws CompilationError
 */
export const ListFunctions_async = defineFunction("user.ListFunctions", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<FunctionInfo[]>;

/**
 * The result of a reflective invocation: exactly one of `value` (success)
 * or `error_type` + `error_message` (failure) is populated.
 */
export class InvokeResult {
  ok!: boolean;
  value!: unknown | null;
  error_type!: string | null;
  error_message!: string | null;
  constructor(init: {
    ok: boolean;
    value: unknown | null;
    error_type: string | null;
    error_message: string | null;
  }) {
    Object.assign(this, init);
  }
}

export const _decode_arg = defineFunction("user._decode_arg", "sync", ["raw_json", "t"]) as (raw_json: string, t: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => InvokeResult;

export const _decode_arg_async = defineFunction("user._decode_arg", "async", ["raw_json", "t"]) as (raw_json: string, t: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<InvokeResult>;

/**
 * Calls the function named `name` with `args` (each value pre-encoded as a
 * JSON string, decoded against the parameter's *reflected* type), entirely
 * through `reflect.call_any` — no per-function branch anywhere in this file.
 * 
 * `name` need not be a "demo" function: passing a compiler-synthesized
 * companion like `root.SummarizeText$parse` works exactly the same way,
 * which is how mock mode replays a canned model response (see
 * backend/src/invoke.ts) without this function ever knowing about it.
 * @throws CompilationError
 */
export const InvokeFunction = defineFunction("user.InvokeFunction", "sync", ["name", "args"]) as (name: string, args: { [key: string]: string }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => InvokeResult;

/**
 * Calls the function named `name` with `args` (each value pre-encoded as a
 * JSON string, decoded against the parameter's *reflected* type), entirely
 * through `reflect.call_any` — no per-function branch anywhere in this file.
 * 
 * `name` need not be a "demo" function: passing a compiler-synthesized
 * companion like `root.SummarizeText$parse` works exactly the same way,
 * which is how mock mode replays a canned model response (see
 * backend/src/invoke.ts) without this function ever knowing about it.
 * @throws CompilationError
 */
export const InvokeFunction_async = defineFunction("user.InvokeFunction", "async", ["name", "args"]) as (name: string, args: { [key: string]: string }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<InvokeResult>;
