/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type { BamlHandle as _BamlHandle } from "@boundaryml/baml-bridge";
import { defineFunction, defineInstanceFunction, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";
import type * as reflect from "../../reflect/index.js";

/**
 * A mutable runtime-class definition. Calling `build` freezes every builder
 * connected through a pending field type as one atomic recursive group.
 */
export class Builder$stream {
  _handle!: _BamlHandle;
  _roots!: unknown[];
  _neighbors!: Builder$stream[];
  _resolved!: unknown | null;
  constructor(init: {
    _handle: _BamlHandle;
    _roots: unknown[];
    _neighbors: Builder$stream[];
    _resolved: unknown | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Attributes:
 *   name
 *   type
 *   meta
 *   _owner: Present only for handles returned from `baml.AnyClass.list_fields` or
 *     `get_field`. Type-side descriptors returned by `Type.fields()` are
 *     intentionally ownerless.
 */
export class Field {
  name!: string;
  type!: BamlType | null;
  meta!: reflect.Meta;
  _owner!: unknown | null;
  constructor(init: {
    name: string;
    type: BamlType | null;
    meta: reflect.Meta;
    _owner: unknown | null;
  }) {
    Object.assign(this, init);
  }
  metadata = defineInstanceFunction("reflect.class.Field.metadata", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => reflect.Meta;
  metadata_async = defineInstanceFunction("reflect.class.Field.metadata", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<reflect.Meta>;
/**
 * Read this field from its bound owner. An ownerless type-side descriptor
 * returns `null`.
 * @throws TypeMismatch
 */
  value = defineInstanceFunction("reflect.class.Field.value", "sync", ["self"], undefined, { typeParams: ["T"] }).bind(this) as <T>($opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T | null;
/**
 * Read this field from its bound owner. An ownerless type-side descriptor
 * returns `null`.
 * @throws TypeMismatch
 */
  value_async = defineInstanceFunction("reflect.class.Field.value", "async", ["self"], undefined, { typeParams: ["T"] }).bind(this) as <T>($opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T | null>;
}

/**
 * Attributes:
 *   name
 *   type
 *   meta
 *   _owner: Present only for handles returned from `baml.AnyClass.list_fields` or
 *     `get_field`. Type-side descriptors returned by `Type.fields()` are
 *     intentionally ownerless.
 */
export class Field$stream {
  name!: string | null;
  type!: unknown | null;
  meta!: reflect.Meta$stream | null;
  _owner!: unknown | null;
  constructor(init: {
    name: string | null;
    type: unknown | null;
    meta: reflect.Meta$stream | null;
    _owner: unknown | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A reference to a not-yet-frozen builder type. It is deliberately not a
 * subtype of the built-in `type`; only Builder.field accepts it directly.
 */
export class PendingType$stream {
  _handle!: _BamlHandle;
  _roots!: unknown[];
  _resolved!: unknown | null;
  constructor(init: {
    _handle: _BamlHandle;
    _roots: unknown[];
    _resolved: unknown | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A class-kind view of a `type` value. Users never construct this class.
 */
export class Type$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

/**
 * Construct a closed runtime class. Map iteration order is definition order.
 * @throws CompilationError
 */
const __baml_new = defineFunction("reflect.class.new", "sync", ["name", "fields"], ["implementations"]) as (name: string, fields: { [key: string]: BamlType | reflect.WithMeta<BamlType> }, $opts?: { implementations?: reflect.interface.Implementation[] | undefined; $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
export { __baml_new as new };

/**
 * Construct a closed runtime class. Map iteration order is definition order.
 * @throws CompilationError
 */
export const new_async = defineFunction("reflect.class.new", "async", ["name", "fields"], ["implementations"]) as (name: string, fields: { [key: string]: BamlType | reflect.WithMeta<BamlType> }, $opts?: { implementations?: reflect.interface.Implementation[] | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;

/**
 * @throws CompilationError
 */
export const _new = defineFunction("reflect.class._new", "sync", ["name", "fields", "implementations"]) as (name: string, fields: { [key: string]: BamlType | reflect.WithMeta<BamlType> }, implementations: reflect.interface.Implementation[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;

/**
 * @throws CompilationError
 */
export const _new_async = defineFunction("reflect.class._new", "async", ["name", "fields", "implementations"]) as (name: string, fields: { [key: string]: BamlType | reflect.WithMeta<BamlType> }, implementations: reflect.interface.Implementation[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;

export const builder = defineFunction("reflect.class.builder", "sync", ["name"]) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Builder;

export const builder_async = defineFunction("reflect.class.builder", "async", ["name"]) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Builder>;

/**
 * A mutable runtime-class definition. Calling `build` freezes every builder
 * connected through a pending field type as one atomic recursive group.
 */
export class Builder {
  _handle!: _BamlHandle;
  _roots!: unknown[];
  _neighbors!: Builder[];
  _resolved!: BamlType | null;
  constructor(init: {
    _handle: _BamlHandle;
    _roots: unknown[];
    _neighbors: Builder[];
    _resolved: BamlType | null;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws CompilationError
 */
  field = defineInstanceFunction("reflect.class.Builder.field", "sync", ["self", "name", "ty"]).bind(this) as (name: string, ty: BamlType | reflect.WithMeta<BamlType> | PendingType | reflect.WithMeta<PendingType>, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Builder;
/**
 * @throws CompilationError
 */
  field_async = defineInstanceFunction("reflect.class.Builder.field", "async", ["self", "name", "ty"]).bind(this) as (name: string, ty: BamlType | reflect.WithMeta<BamlType> | PendingType | reflect.WithMeta<PendingType>, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Builder>;
  type = defineInstanceFunction("reflect.class.Builder.type", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => PendingType;
  type_async = defineInstanceFunction("reflect.class.Builder.type", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<PendingType>;
/**
 * Validate and freeze this builder's complete connected recursive group.
 * @throws CompilationError
 */
  build = defineInstanceFunction("reflect.class.Builder.build", "sync", ["self"], ["implementations"]).bind(this) as ($opts?: { implementations?: reflect.interface.Implementation[] | undefined; $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
/**
 * Validate and freeze this builder's complete connected recursive group.
 * @throws CompilationError
 */
  build_async = defineInstanceFunction("reflect.class.Builder.build", "async", ["self"], ["implementations"]).bind(this) as ($opts?: { implementations?: reflect.interface.Implementation[] | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;
/**
 * @throws CompilationError
 */
  _build = defineInstanceFunction("reflect.class.Builder._build", "sync", ["self", "implementations"]).bind(this) as (implementations: reflect.interface.Implementation[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
/**
 * @throws CompilationError
 */
  _build_async = defineInstanceFunction("reflect.class.Builder._build", "async", ["self", "implementations"]).bind(this) as (implementations: reflect.interface.Implementation[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;
}

/**
 * A reference to a not-yet-frozen builder type. It is deliberately not a
 * subtype of the built-in `type`; only Builder.field accepts it directly.
 */
export class PendingType {
  _handle!: _BamlHandle;
  _roots!: unknown[];
  _resolved!: BamlType | null;
  constructor(init: {
    _handle: _BamlHandle;
    _roots: unknown[];
    _resolved: BamlType | null;
  }) {
    Object.assign(this, init);
  }
  array = defineInstanceFunction("reflect.class.PendingType.array", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => PendingType;
  array_async = defineInstanceFunction("reflect.class.PendingType.array", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<PendingType>;
  optional = defineInstanceFunction("reflect.class.PendingType.optional", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => PendingType;
  optional_async = defineInstanceFunction("reflect.class.PendingType.optional", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<PendingType>;
  union = defineInstanceFunction("reflect.class.PendingType.union", "sync", ["self", "others"]).bind(this) as (others: (BamlType | PendingType)[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => PendingType;
  union_async = defineInstanceFunction("reflect.class.PendingType.union", "async", ["self", "others"]).bind(this) as (others: (BamlType | PendingType)[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<PendingType>;
  resolved = defineInstanceFunction("reflect.class.PendingType.resolved", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType | null;
  resolved_async = defineInstanceFunction("reflect.class.PendingType.resolved", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType | null>;
  meta = defineInstanceFunction("reflect.class.PendingType.meta", "sync", ["self"], ["alias", "description", "docstring", "other"]).bind(this) as ($opts?: { alias?: string | null | undefined; description?: string | null | undefined; docstring?: string | null | undefined; other?: { [key: string]: string } | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => reflect.WithMeta<PendingType>;
  meta_async = defineInstanceFunction("reflect.class.PendingType.meta", "async", ["self"], ["alias", "description", "docstring", "other"]).bind(this) as ($opts?: { alias?: string | null | undefined; description?: string | null | undefined; docstring?: string | null | undefined; other?: { [key: string]: string } | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<reflect.WithMeta<PendingType>>;
}

/**
 * @throws CompilationError
 */
export const get_field = defineFunction("reflect.class.get_field", "sync", ["value", "name"], undefined, { typeParams: ["T"] }) as <T>(value: unknown, name: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;

/**
 * @throws CompilationError
 */
export const get_field_async = defineFunction("reflect.class.get_field", "async", ["value", "name"], undefined, { typeParams: ["T"] }) as <T>(value: unknown, name: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;

/**
 * A class-kind view of a `type` value. Users never construct this class.
 */
export class Type {
  constructor(init: {}) {
    Object.assign(this, init);
  }
  fields = defineInstanceFunction("reflect.class.Type.fields", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Field[];
  fields_async = defineInstanceFunction("reflect.class.Type.fields", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Field[]>;
  meta = defineInstanceFunction("reflect.class.Type.meta", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => reflect.Meta;
  meta_async = defineInstanceFunction("reflect.class.Type.meta", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<reflect.Meta>;
}
