/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type { BamlHandle as _BamlHandle } from "@boundaryml/baml-bridge";
import { defineFunction, defineInstanceFunction, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";
import type * as ai from "../ai/index.js";
import type * as baml from "../baml/index.js";
export * as clients from "./clients/index.js";
export * as content from "./content/index.js";
export * as errors from "./errors/index.js";
export * as events from "./events/index.js";
export * as internal from "./internal/index.js";
export * as mcp from "./mcp/index.js";
export * as stream from "./stream/index.js";
export * as tools from "./tools/index.js";
export * as wire from "./wire/index.js";

/**
 * Render context accepted by a standalone `prompt` tag closure.
 */
export class Context$stream {
  client!: ContextClient$stream | null;
  tags!: { [key: string]: unknown };
  _output_format!: OutputFormat$stream | null;
  constructor(init: {
    client: ContextClient$stream | null;
    tags: { [key: string]: unknown };
    _output_format: OutputFormat$stream | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Client metadata available to a standalone `prompt` tag body.
 */
export class ContextClient$stream {
  name!: string | null;
  provider!: string | null;
  default_role!: string | null;
  allowed_roles!: string[];
  constructor(init: {
    name: string | null;
    provider: string | null;
    default_role: string | null;
    allowed_roles: string[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Opaque handle to a prebuilt output-format schema. This supports the
 * standalone `prompt` tag's parameterized output-format rendering.
 */
export class OutputFormat$stream {
  _data!: _BamlHandle;
  constructor(init: {
    _data: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A typed chat-role marker produced by `${role("system")}` in a prompt.
 *
 * Attributes:
 *   name
 *   metadata: Provider-specific per-message metadata such as cache control.
 */
export class Role$stream {
  name!: string | null;
  metadata!: { [key: string]: unknown };
  constructor(init: {
    name: string | null;
    metadata: { [key: string]: unknown };
  }) {
    Object.assign(this, init);
  }
}

/**
 * Opaque handle to a prebuilt output-format schema. This supports the
 * standalone `prompt` tag's parameterized output-format rendering.
 */
export class OutputFormat {
  _data!: _BamlHandle;
  constructor(init: {
    _data: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
  _render = defineInstanceFunction("ai.OutputFormat._render", "sync", ["self"], ["prefix", "or_splitter", "enum_value_prefix", "hoisted_class_prefix", "always_hoist_enums", "quote_class_fields", "hoist_classes", "map_style", "render_null_as"]).bind(this) as ($opts?: { prefix?: string | ai.internal.OutputFormatDefault | null | undefined; or_splitter?: string | ai.internal.OutputFormatDefault | undefined; enum_value_prefix?: string | ai.internal.OutputFormatDefault | null | undefined; hoisted_class_prefix?: string | ai.internal.OutputFormatDefault | null | undefined; always_hoist_enums?: boolean | ai.internal.OutputFormatDefault | undefined; quote_class_fields?: boolean | ai.internal.OutputFormatDefault | undefined; hoist_classes?: boolean | "auto" | string[] | ai.internal.OutputFormatDefault | undefined; map_style?: "angle" | "object" | ai.internal.OutputFormatDefault | undefined; render_null_as?: string | ai.internal.OutputFormatDefault | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => string;
  _render_async = defineInstanceFunction("ai.OutputFormat._render", "async", ["self"], ["prefix", "or_splitter", "enum_value_prefix", "hoisted_class_prefix", "always_hoist_enums", "quote_class_fields", "hoist_classes", "map_style", "render_null_as"]).bind(this) as ($opts?: { prefix?: string | ai.internal.OutputFormatDefault | null | undefined; or_splitter?: string | ai.internal.OutputFormatDefault | undefined; enum_value_prefix?: string | ai.internal.OutputFormatDefault | null | undefined; hoisted_class_prefix?: string | ai.internal.OutputFormatDefault | null | undefined; always_hoist_enums?: boolean | ai.internal.OutputFormatDefault | undefined; quote_class_fields?: boolean | ai.internal.OutputFormatDefault | undefined; hoist_classes?: boolean | "auto" | string[] | ai.internal.OutputFormatDefault | undefined; map_style?: "angle" | "object" | ai.internal.OutputFormatDefault | undefined; render_null_as?: string | ai.internal.OutputFormatDefault | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
}

/**
 * A typed chat-role marker produced by `${role("system")}` in a prompt.
 *
 * Attributes:
 *   name
 *   metadata: Provider-specific per-message metadata such as cache control.
 */
export class Role {
  name!: string;
  metadata!: { [key: string]: unknown };
  constructor(init: {
    name: string;
    metadata: { [key: string]: unknown };
  }) {
    Object.assign(this, init);
  }
}

/**
 * Client metadata available to a standalone `prompt` tag body.
 */
export class ContextClient {
  name!: string;
  provider!: string;
  default_role!: string;
  allowed_roles!: string[];
  constructor(init: {
    name: string;
    provider: string;
    default_role: string;
    allowed_roles: string[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Render context accepted by a standalone `prompt` tag closure.
 */
export class Context {
  client!: ContextClient;
  tags!: { [key: string]: unknown };
  _output_format!: OutputFormat;
  constructor(init: {
    client: ContextClient;
    tags: { [key: string]: unknown };
    _output_format: OutputFormat;
  }) {
    Object.assign(this, init);
  }
  output_format = defineInstanceFunction("ai.Context.output_format", "sync", ["self"], ["prefix", "or_splitter", "enum_value_prefix", "hoisted_class_prefix", "always_hoist_enums", "quote_class_fields", "hoist_classes", "map_style", "render_null_as"]).bind(this) as ($opts?: { prefix?: string | ai.internal.OutputFormatDefault | null | undefined; or_splitter?: string | ai.internal.OutputFormatDefault | undefined; enum_value_prefix?: string | ai.internal.OutputFormatDefault | null | undefined; hoisted_class_prefix?: string | ai.internal.OutputFormatDefault | null | undefined; always_hoist_enums?: boolean | ai.internal.OutputFormatDefault | undefined; quote_class_fields?: boolean | ai.internal.OutputFormatDefault | undefined; hoist_classes?: boolean | "auto" | string[] | ai.internal.OutputFormatDefault | undefined; map_style?: "angle" | "object" | ai.internal.OutputFormatDefault | undefined; render_null_as?: string | ai.internal.OutputFormatDefault | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => string;
  output_format_async = defineInstanceFunction("ai.Context.output_format", "async", ["self"], ["prefix", "or_splitter", "enum_value_prefix", "hoisted_class_prefix", "always_hoist_enums", "quote_class_fields", "hoist_classes", "map_style", "render_null_as"]).bind(this) as ($opts?: { prefix?: string | ai.internal.OutputFormatDefault | null | undefined; or_splitter?: string | ai.internal.OutputFormatDefault | undefined; enum_value_prefix?: string | ai.internal.OutputFormatDefault | null | undefined; hoisted_class_prefix?: string | ai.internal.OutputFormatDefault | null | undefined; always_hoist_enums?: boolean | ai.internal.OutputFormatDefault | undefined; quote_class_fields?: boolean | ai.internal.OutputFormatDefault | undefined; hoist_classes?: boolean | "auto" | string[] | ai.internal.OutputFormatDefault | undefined; map_style?: "angle" | "object" | ai.internal.OutputFormatDefault | undefined; render_null_as?: string | ai.internal.OutputFormatDefault | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
}

export class Journal$stream {
  log!: ai.events.Event$stream[];
  constructor(init: {
    log: ai.events.Event$stream[];
  }) {
    Object.assign(this, init);
  }
}

export class Journal {
  log!: ai.events.Event[];
  constructor(init: {
    log: ai.events.Event[];
  }) {
    Object.assign(this, init);
  }
  static new = defineFunction("ai.Journal.new", "sync", ["spec"], undefined, { typeParams: ["Out"] }) as <Out>(spec: FunctionSpec<Out>, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { Out?: BamlType | BamlTypeToken } | undefined } | undefined) => Journal;
  static new_async = defineFunction("ai.Journal.new", "async", ["spec"], undefined, { typeParams: ["Out"] }) as <Out>(spec: FunctionSpec<Out>, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { Out?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<Journal>;
  entries = defineInstanceFunction("ai.Journal.entries", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.events.Event[];
  entries_async = defineInstanceFunction("ai.Journal.entries", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.events.Event[]>;
  append_all = defineInstanceFunction("ai.Journal.append_all", "sync", ["self", "events"]).bind(this) as (events: ai.events.Event[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
  append_all_async = defineInstanceFunction("ai.Journal.append_all", "async", ["self", "events"]).bind(this) as (events: ai.events.Event[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
}

export class Agent$stream {
  max_steps!: number | null;
  schema_attempts!: number | null;
  client!: unknown | null;
  tool_errors!: ai.tools.ErrorMode | null;
  on_event!: unknown | null;
  constructor(init: {
    max_steps: number | null;
    schema_attempts: number | null;
    client: unknown | null;
    tool_errors: ai.tools.ErrorMode | null;
    on_event: unknown | null;
  }) {
    Object.assign(this, init);
  }
}

export class RunResult$stream<Out> {
  value!: Out | null;
  journal!: Journal$stream | null;
  usage!: ai.events.Usage$stream | null;
  $types?: { Out?: BamlType | BamlTypeToken };
  constructor(init: {
    value: Out | null;
    journal: Journal$stream | null;
    usage: ai.events.Usage$stream | null;
    $types?: { Out?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["Out"] as const;
}

export class RunResult<Out> {
  value!: Out;
  journal!: Journal;
  usage!: ai.events.Usage;
  $types?: { Out?: BamlType | BamlTypeToken };
  constructor(init: {
    value: Out;
    journal: Journal;
    usage: ai.events.Usage;
    $types?: { Out?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["Out"] as const;
}

export class Agent {
  max_steps!: number;
  schema_attempts!: number;
  client!: unknown | null;
  tool_errors!: ai.tools.ErrorMode;
  on_event!: ((arg0: ai.events.Event) => null) | null;
  constructor(init: {
    max_steps: number;
    schema_attempts: number;
    client: unknown | null;
    tool_errors: ai.tools.ErrorMode;
    on_event: ((arg0: ai.events.Event) => null) | null;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws InvalidArgument
 */
  static new = defineFunction("ai.Agent.new", "sync", [], ["max_steps", "schema_attempts", "client", "tool_errors", "on_event"]) as ($opts?: { max_steps?: number | undefined; schema_attempts?: number | undefined; client?: unknown | null | undefined; tool_errors?: ai.tools.ErrorMode | undefined; on_event?: ((arg0: ai.events.Event) => null) | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Agent;
/**
 * @throws InvalidArgument
 */
  static new_async = defineFunction("ai.Agent.new", "async", [], ["max_steps", "schema_attempts", "client", "tool_errors", "on_event"]) as ($opts?: { max_steps?: number | undefined; schema_attempts?: number | undefined; client?: unknown | null | undefined; tool_errors?: ai.tools.ErrorMode | undefined; on_event?: ((arg0: ai.events.Event) => null) | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Agent>;
/**
 * @throws InvalidArgument
 */
  _validated_schema_attempts = defineInstanceFunction("ai.Agent._validated_schema_attempts", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => number;
/**
 * @throws InvalidArgument
 */
  _validated_schema_attempts_async = defineInstanceFunction("ai.Agent._validated_schema_attempts", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<number>;
/**
 * @throws ToolFailedError
 */
  _run_one_tool = defineInstanceFunction("ai.Agent._run_one_tool", "sync", ["self", "tb", "call", "j"]).bind(this) as (tb: ai.tools.Toolbox, call: ai.content.ToolUse, j: Journal, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * @throws ToolFailedError
 */
  _run_one_tool_async = defineInstanceFunction("ai.Agent._run_one_tool", "async", ["self", "tb", "call", "j"]).bind(this) as (tb: ai.tools.Toolbox, call: ai.content.ToolUse, j: Journal, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
/**
 * @throws UnknownError
 */
  _has_media_output = defineInstanceFunction("ai.Agent._has_media_output", "sync", ["self", "turn"], undefined, { typeParams: ["Out"] }).bind(this) as <Out>(turn: ModelTurn, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { Out?: BamlType | BamlTypeToken } | undefined } | undefined) => boolean;
/**
 * @throws UnknownError
 */
  _has_media_output_async = defineInstanceFunction("ai.Agent._has_media_output", "async", ["self", "turn"], undefined, { typeParams: ["Out"] }).bind(this) as <Out>(turn: ModelTurn, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { Out?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<boolean>;
/**
 * @throws ParseFailed
 * @throws UnknownError
 */
  _media_value = defineInstanceFunction("ai.Agent._media_value", "sync", ["self", "turn", "provider"], undefined, { typeParams: ["Out"] }).bind(this) as <Out>(turn: ModelTurn, provider: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { Out?: BamlType | BamlTypeToken } | undefined } | undefined) => Out;
/**
 * @throws ParseFailed
 * @throws UnknownError
 */
  _media_value_async = defineInstanceFunction("ai.Agent._media_value", "async", ["self", "turn", "provider"], undefined, { typeParams: ["Out"] }).bind(this) as <Out>(turn: ModelTurn, provider: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { Out?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<Out>;
/**
 * @throws UnknownError
 */
  _parses = defineInstanceFunction("ai.Agent._parses", "sync", ["self", "turn", "candidate"], undefined, { typeParams: ["Out"] }).bind(this) as <Out>(turn: ModelTurn, candidate: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { Out?: BamlType | BamlTypeToken } | undefined } | undefined) => boolean;
/**
 * @throws UnknownError
 */
  _parses_async = defineInstanceFunction("ai.Agent._parses", "async", ["self", "turn", "candidate"], undefined, { typeParams: ["Out"] }).bind(this) as <Out>(turn: ModelTurn, candidate: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { Out?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<boolean>;
/**
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
  _attempt_turn = defineInstanceFunction("ai.Agent._attempt_turn", "sync", ["self", "c", "spec", "j", "total", "attempts_left"], undefined, { typeParams: ["Out"] }).bind(this) as <Out>(c: unknown, spec: FunctionSpec<Out>, j: Journal, total: ai.events.Usage, attempts_left: number, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { Out?: BamlType | BamlTypeToken } | undefined } | undefined) => ModelTurn;
/**
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
  _attempt_turn_async = defineInstanceFunction("ai.Agent._attempt_turn", "async", ["self", "c", "spec", "j", "total", "attempts_left"], undefined, { typeParams: ["Out"] }).bind(this) as <Out>(c: unknown, spec: FunctionSpec<Out>, j: Journal, total: ai.events.Usage, attempts_left: number, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { Out?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<ModelTurn>;
  _emit_from = defineInstanceFunction("ai.Agent._emit_from", "sync", ["self", "j", "seen"]).bind(this) as (j: Journal, seen: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => number;
  _emit_from_async = defineInstanceFunction("ai.Agent._emit_from", "async", ["self", "j", "seen"]).bind(this) as (j: Journal, seen: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<number>;
}

export class FunctionSpec$stream<Out> {
  spec_name!: string | null;
  args!: { [key: string]: unknown };
  prompt_template!: unknown;
  toolbox!: ai.tools.Toolbox$stream | null;
  default_client!: unknown | null;
  $types?: { Out?: BamlType | BamlTypeToken };
  constructor(init: {
    spec_name: string | null;
    args: { [key: string]: unknown };
    prompt_template: unknown;
    toolbox: ai.tools.Toolbox$stream | null;
    default_client: unknown | null;
    $types?: { Out?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["Out"] as const;
}

/**
 * The rendered, provider-neutral prompt passed to clients. Roles split the
 * prompt into messages and media remains structural until a provider lowers
 * it to its wire format.
 */
export class Prompt$stream {
  _data!: _BamlHandle;
  constructor(init: {
    _data: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A single chat message in a rendered prompt.
 *
 * Attributes:
 *   role: The chat role, e.g. "system", "user", or "assistant". Empty for
 *     role-less content.
 *   content: The message's rendered text. Media parts use a readable placeholder.
 *   parts: Ordered structural content. Provider clients use this instead of the
 *     readable `content` projection so media survives prompt rendering.
 *   metadata: Per-message provider directives, carried verbatim from the
 *     `root.Role.metadata` of the `${role(...)}` marker that opened
 *     this message — Anthropic `cache_control`, for example. Empty when the
 *     message carried none.
 */
export class PromptMessage$stream {
  role!: string | null;
  content!: string | null;
  parts!: PromptPart$stream[];
  metadata!: { [key: string]: baml.json.json$stream };
  constructor(init: {
    role: string | null;
    content: string | null;
    parts: PromptPart$stream[];
    metadata: { [key: string]: baml.json.json$stream };
  }) {
    Object.assign(this, init);
  }
}

export type ClientSelector$stream = ai.clients.ClientSelector$stream;

export type Credential$stream = string | baml.env.Ref$stream;

export type MediaPart$stream = baml.media.Image$stream | baml.media.Audio$stream | baml.media.Video$stream | baml.media.Pdf$stream;

export type PromptPart$stream = string | MediaPart$stream;

export type Credential = string | baml.env.Ref;

export type ClientSelector = ai.clients.ClientSelector;

export type MediaPart = baml.media.Image | baml.media.Audio | baml.media.Video | baml.media.Pdf;

export type PromptPart = string | MediaPart;

/**
 * A single chat message in a rendered prompt.
 *
 * Attributes:
 *   role: The chat role, e.g. "system", "user", or "assistant". Empty for
 *     role-less content.
 *   content: The message's rendered text. Media parts use a readable placeholder.
 *   parts: Ordered structural content. Provider clients use this instead of the
 *     readable `content` projection so media survives prompt rendering.
 *   metadata: Per-message provider directives, carried verbatim from the
 *     `root.Role.metadata` of the `${role(...)}` marker that opened
 *     this message — Anthropic `cache_control`, for example. Empty when the
 *     message carried none.
 */
export class PromptMessage {
  role!: string;
  content!: string;
  parts!: PromptPart[];
  metadata!: { [key: string]: baml.json.json };
  constructor(init: {
    role: string;
    content: string;
    parts: PromptPart[];
    metadata: { [key: string]: baml.json.json };
  }) {
    Object.assign(this, init);
  }
}

/**
 * The rendered, provider-neutral prompt passed to clients. Roles split the
 * prompt into messages and media remains structural until a provider lowers
 * it to its wire format.
 */
export class Prompt {
  _data!: _BamlHandle;
  constructor(init: {
    _data: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
  text = defineInstanceFunction("ai.Prompt.text", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;
  text_async = defineInstanceFunction("ai.Prompt.text", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
  messages = defineInstanceFunction("ai.Prompt.messages", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => PromptMessage[];
  messages_async = defineInstanceFunction("ai.Prompt.messages", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<PromptMessage[]>;
}

export const prompt = defineFunction("ai.prompt", "sync", ["body"]) as (body: (role: (arg0: string) => Role, ctx: Context) => baml.TaggedString, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => (arg0: Context) => Prompt;

export const prompt_async = defineFunction("ai.prompt", "async", ["body"]) as (body: (role: (arg0: string) => Role, ctx: Context) => baml.TaggedString, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<(arg0: Context) => Prompt>;

export class FunctionSpec<Out> {
  spec_name!: string;
  args!: { [key: string]: unknown };
  prompt_template!: (arg0: OutputFormat) => Prompt;
  toolbox!: ai.tools.Toolbox;
  default_client!: unknown;
  $types?: { Out?: BamlType | BamlTypeToken };
  constructor(init: {
    spec_name: string;
    args: { [key: string]: unknown };
    prompt_template: (arg0: OutputFormat) => Prompt;
    toolbox: ai.tools.Toolbox;
    default_client: unknown;
    $types?: { Out?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["Out"] as const;
/**
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
  build_request = defineInstanceFunction("ai.FunctionSpec.build_request", "sync", ["self"], ["override_client"], { classTypeParams: ["Out"] }).bind(this) as ($opts?: { override_client?: unknown | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => baml.http.Request;
/**
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
  build_request_async = defineInstanceFunction("ai.FunctionSpec.build_request", "async", ["self"], ["override_client"], { classTypeParams: ["Out"] }).bind(this) as ($opts?: { override_client?: unknown | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.http.Request>;
  name = defineInstanceFunction("ai.FunctionSpec.name", "sync", ["self"], undefined, { classTypeParams: ["Out"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;
  name_async = defineInstanceFunction("ai.FunctionSpec.name", "async", ["self"], undefined, { classTypeParams: ["Out"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
  arguments = defineInstanceFunction("ai.FunctionSpec.arguments", "sync", ["self"], undefined, { classTypeParams: ["Out"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => { [key: string]: unknown };
  arguments_async = defineInstanceFunction("ai.FunctionSpec.arguments", "async", ["self"], undefined, { classTypeParams: ["Out"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<{ [key: string]: unknown }>;
/**
 * @throws CompilationError
 */
  output_type = defineInstanceFunction("ai.FunctionSpec.output_type", "sync", ["self"], undefined, { classTypeParams: ["Out"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
/**
 * @throws CompilationError
 */
  output_type_async = defineInstanceFunction("ai.FunctionSpec.output_type", "async", ["self"], undefined, { classTypeParams: ["Out"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;
/**
 * @throws PromptRenderError
 * @throws CompilationError
 */
  prompt = defineInstanceFunction("ai.FunctionSpec.prompt", "sync", ["self"], undefined, { classTypeParams: ["Out"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Prompt;
/**
 * @throws PromptRenderError
 * @throws CompilationError
 */
  prompt_async = defineInstanceFunction("ai.FunctionSpec.prompt", "async", ["self"], undefined, { classTypeParams: ["Out"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Prompt>;
  tools = defineInstanceFunction("ai.FunctionSpec.tools", "sync", ["self"], undefined, { classTypeParams: ["Out"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.tools.Toolbox;
  tools_async = defineInstanceFunction("ai.FunctionSpec.tools", "async", ["self"], undefined, { classTypeParams: ["Out"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.tools.Toolbox>;
}

export class ModelTurn$stream {
  content!: ai.content.Block$stream[];
  stop_reason!: ai.content.StopReason | null;
  usage!: ai.events.Usage$stream | null;
  calls!: ai.events.LLMCall$stream[];
  constructor(init: {
    content: ai.content.Block$stream[];
    stop_reason: ai.content.StopReason | null;
    usage: ai.events.Usage$stream | null;
    calls: ai.events.LLMCall$stream[];
  }) {
    Object.assign(this, init);
  }
}

export class ModelTurnInput$stream {
  prompt!: unknown;
  journal!: Journal$stream | null;
  toolbox!: ai.tools.Toolbox$stream | null;
  output_type!: unknown;
  constructor(init: {
    prompt: unknown;
    journal: Journal$stream | null;
    toolbox: ai.tools.Toolbox$stream | null;
    output_type: unknown;
  }) {
    Object.assign(this, init);
  }
}

export class ModelTurnInput {
  prompt!: (arg0: OutputFormat) => Prompt;
  journal!: Journal;
  toolbox!: ai.tools.Toolbox;
  output_type!: BamlType;
  constructor(init: {
    prompt: (arg0: OutputFormat) => Prompt;
    journal: Journal;
    toolbox: ai.tools.Toolbox;
    output_type: BamlType;
  }) {
    Object.assign(this, init);
  }
}

export class ModelTurn {
  content!: ai.content.Block[];
  stop_reason!: ai.content.StopReason;
  usage!: ai.events.Usage | null;
  calls!: ai.events.LLMCall[];
  constructor(init: {
    content: ai.content.Block[];
    stop_reason: ai.content.StopReason;
    usage: ai.events.Usage | null;
    calls: ai.events.LLMCall[];
  }) {
    Object.assign(this, init);
  }
  terminal_text = defineInstanceFunction("ai.ModelTurn.terminal_text", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;
  terminal_text_async = defineInstanceFunction("ai.ModelTurn.terminal_text", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;
  media = defineInstanceFunction("ai.ModelTurn.media", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => MediaPart[];
  media_async = defineInstanceFunction("ai.ModelTurn.media", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<MediaPart[]>;
  tool_uses = defineInstanceFunction("ai.ModelTurn.tool_uses", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.content.ToolUse[];
  tool_uses_async = defineInstanceFunction("ai.ModelTurn.tool_uses", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.content.ToolUse[]>;
}

/** Erased runtime token for BAML interface `ai.Client`. */
export const Client = Object.freeze({ __baml_interface_fqn__: "ai.Client" } as const);
