/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, initializeRuntimeFromBytecode, setTypeMap, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";
import * as _inlinedbaml from "./_inlinedbaml.js";
import { _TYPE_MAP } from "./_typemap.js";
import type * as ai from "./ai/index.js";
import type * as baml from "./baml/index.js";

initializeRuntimeFromBytecode(_inlinedbaml.BYTECODE, _inlinedbaml.BAML_TOML);
setTypeMap(_TYPE_MAP);

export * as ai from "./ai/index.js";
export * as baml from "./baml/index.js";
export * as reflect from "./reflect/index.js";
export * as vendor from "./vendor/index.js";

/**
 * One row from the team's editable category list.
 */
export class CategoryInput$stream {
  id!: number | null;
  name!: string | null;
  description!: string | null;
  constructor(init: {
    id: number | null;
    name: string | null;
    description: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * One row from the team's editable category list.
 */
export class CategoryInput {
  id!: number;
  name!: string;
  description!: string | null;
  constructor(init: {
    id: number;
    name: string;
    description: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Classify a ticket into `T`. The caller supplies the type — freshly minted, per call.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const classify = defineFunction("user.classify", "sync", ["ticket_text"], undefined, { typeParams: ["T"] }) as <T>(ticket_text: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;

/**
 * Classify a ticket into `T`. The caller supplies the type — freshly minted, per call.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const classify_async = defineFunction("user.classify", "async", ["ticket_text"], undefined, { typeParams: ["T"] }) as <T>(ticket_text: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;

/**
 * Classify a ticket into `T`. The caller supplies the type — freshly minted, per call.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const classify$build_request = defineFunction("user.classify$build_request", "sync", ["ticket_text"], undefined, { typeParams: ["T"] }) as <T>(ticket_text: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => baml.http.Request;

/**
 * Classify a ticket into `T`. The caller supplies the type — freshly minted, per call.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const classify$build_request_async = defineFunction("user.classify$build_request", "async", ["ticket_text"], undefined, { typeParams: ["T"] }) as <T>(ticket_text: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * Classify a ticket into `T`. The caller supplies the type — freshly minted, per call.
 * @throws LlmClient
 */
export const classify$parse = defineFunction("user.classify$parse", "sync", ["json"], undefined, { typeParams: ["T"] }) as <T>(json: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;

/**
 * Classify a ticket into `T`. The caller supplies the type — freshly minted, per call.
 * @throws LlmClient
 */
export const classify$parse_async = defineFunction("user.classify$parse", "async", ["json"], undefined, { typeParams: ["T"] }) as <T>(json: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;

/**
 * Classify a ticket into `T`. The caller supplies the type — freshly minted, per call.
 * @throws InvalidArgument
 * @throws CompilationError
 */
export const classify$render_prompt = defineFunction("user.classify$render_prompt", "sync", ["ticket_text"], undefined, { typeParams: ["T"] }) as <T>(ticket_text: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => ai.Prompt;

/**
 * Classify a ticket into `T`. The caller supplies the type — freshly minted, per call.
 * @throws InvalidArgument
 * @throws CompilationError
 */
export const classify$render_prompt_async = defineFunction("user.classify$render_prompt", "async", ["ticket_text"], undefined, { typeParams: ["T"] }) as <T>(ticket_text: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<ai.Prompt>;

/**
 * Classify a ticket into `T`. The caller supplies the type — freshly minted, per call.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const classify$stream = defineFunction("user.classify$stream", "sync", ["ticket_text"], undefined, { typeParams: ["T"] }) as <T>(ticket_text: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => ai.stream.Stream<T | null, T>;

/**
 * Classify a ticket into `T`. The caller supplies the type — freshly minted, per call.
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const classify$stream_async = defineFunction("user.classify$stream", "async", ["ticket_text"], undefined, { typeParams: ["T"] }) as <T>(ticket_text: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<ai.stream.Stream<T | null, T>>;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const classify_ticket = defineFunction("user.classify_ticket", "sync", ["ticket_text", "categories"]) as (ticket_text: string, categories: CategoryInput[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const classify_ticket_async = defineFunction("user.classify_ticket", "async", ["ticket_text", "categories"]) as (ticket_text: string, categories: CategoryInput[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
