/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { type BamlType } from "@boundaryml/baml-bridge";

/**
 * A primitive-kind view of a `type` value. Users never construct this class.
 *
 * Attributes:
 *   _ty: The wrapped `type` value. Private by invariant: reflection natives are
 *     its only readers, and each kind method panics if the held type no longer
 *     classifies as this view's kind.
 */
export class Type$stream {
  _ty!: unknown;
  constructor(init: {
    _ty: unknown;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A primitive-kind view of a `type` value. Users never construct this class.
 *
 * Attributes:
 *   _ty: The wrapped `type` value. Private by invariant: reflection natives are
 *     its only readers, and each kind method panics if the held type no longer
 *     classifies as this view's kind.
 */
export class Type {
  _ty!: BamlType;
  constructor(init: {
    _ty: BamlType;
  }) {
    Object.assign(this, init);
  }
}
