/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type { BamlHandle as _BamlHandle } from "@boundaryml/baml-bridge";
import { defineFunction, defineInstanceFunction, type BamlCallContext } from "@boundaryml/baml-bridge";
import type * as baml from "../../baml/index.js";

/**
 * A live child process created with `start_process`.
 * 
 * `stdin` and `stdout` are always caller-owned pipes. `stderr` is populated
 * only when `ProcessOptions.stderr` is `StderrMode.Pipe`.
 */
export class Process$stream {
  _handle!: _BamlHandle;
  stdin!: WritePipe$stream | null;
  stdout!: ReadPipe$stream | null;
  stderr!: ReadPipe$stream | null;
  constructor(init: {
    _handle: _BamlHandle;
    stdin: WritePipe$stream | null;
    stdout: ReadPipe$stream | null;
    stderr: ReadPipe$stream | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * The terminal status of a process created with `start_process`.
 */
export class ProcessExit$stream {
  exit_code!: number | null;
  signal!: string | null;
  constructor(init: {
    exit_code: number | null;
    signal: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Options for `exec`, `start_process`, and `shell`.
 *
 * Attributes:
 *   cwd: Working directory for the child process.
 *   env: Environment variables to set for the child process.
 *   timeout_ms: Maximum time in milliseconds to wait for the process to complete.
 *   stdin: The child process's complete stdin. `start_process` writes it and then
 *     closes the pipe. Leave it unset to drive `Process.stdin` incrementally.
 *   stderr: Where the child's stderr goes. `null` means `StderrMode.Inherit`, and
 *     only `StderrMode.Pipe` populates `Process.stderr`.
 */
export class ProcessOptions$stream {
  cwd!: string | null;
  env!: { [key: string]: string } | null;
  timeout_ms!: number | null;
  stdin!: string | null;
  stderr!: StderrMode | null;
  constructor(init: {
    cwd: string | null;
    env: { [key: string]: string } | null;
    timeout_ms: number | null;
    stdin: string | null;
    stderr: StderrMode | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A system pipe for reading data, typically from another process.
 */
export class ReadPipe$stream {
  _pipe!: _BamlHandle;
  constructor(init: {
    _pipe: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A line-oriented view over a `ReadPipe`.
 * 
 * It reads through to the pipe on demand and holds only bytes past the last
 * newline. The final unterminated line is yielded at EOF. Invalid UTF-8 is
 * replaced with U+FFFD.
 */
export class ReadPipeLines$stream {
  pipe!: ReadPipe$stream | null;
  _pending!: Uint8Array;
  constructor(init: {
    pipe: ReadPipe$stream | null;
    _pending: Uint8Array;
  }) {
    Object.assign(this, init);
  }
}

/**
 * The result of running an external process with `exec` or `shell`.
 */
export class ShellOutput$stream {
  stdout!: Uint8Array;
  stderr!: Uint8Array;
  exit_code!: number | null;
  constructor(init: {
    stdout: Uint8Array;
    stderr: Uint8Array;
    exit_code: number | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A system pipe for writing data, typically to another process.
 */
export class WritePipe$stream {
  _pipe!: _BamlHandle;
  constructor(init: {
    _pipe: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Options for `exec`, `start_process`, and `shell`.
 *
 * Attributes:
 *   cwd: Working directory for the child process.
 *   env: Environment variables to set for the child process.
 *   timeout_ms: Maximum time in milliseconds to wait for the process to complete.
 *   stdin: The child process's complete stdin. `start_process` writes it and then
 *     closes the pipe. Leave it unset to drive `Process.stdin` incrementally.
 *   stderr: Where the child's stderr goes. `null` means `StderrMode.Inherit`, and
 *     only `StderrMode.Pipe` populates `Process.stderr`.
 */
export class ProcessOptions {
  cwd!: string | null;
  env!: { [key: string]: string } | null;
  timeout_ms!: number | null;
  stdin!: string | null;
  stderr!: StderrMode | null;
  constructor(init: {
    cwd: string | null;
    env: { [key: string]: string } | null;
    timeout_ms: number | null;
    stdin: string | null;
    stderr: StderrMode | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Where a child process's standard error goes.
 *
 * Members:
 *   Inherit: The child writes to this process's stderr. This is the default.
 *   Pipe: The child's stderr becomes `Process.stderr`. The caller must drain it
 *     concurrently with stdout to prevent the child from blocking.
 *   Discard: The child's stderr is discarded.
 */
export enum StderrMode {
  Inherit = "Inherit",
  Pipe = "Pipe",
  Discard = "Discard",
}

/**
 * The result of running an external process with `exec` or `shell`.
 */
export class ShellOutput {
  stdout!: Uint8Array;
  stderr!: Uint8Array;
  exit_code!: number;
  constructor(init: {
    stdout: Uint8Array;
    stderr: Uint8Array;
    exit_code: number;
  }) {
    Object.assign(this, init);
  }
/**
 * Returns `true` if the process exited with code `0`.
 */
  ok = defineInstanceFunction("baml.sys.ShellOutput.ok", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => boolean;
/**
 * Returns `true` if the process exited with code `0`.
 */
  ok_async = defineInstanceFunction("baml.sys.ShellOutput.ok", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<boolean>;
}

/**
 * The terminal status of a process created with `start_process`.
 */
export class ProcessExit {
  exit_code!: number;
  signal!: string | null;
  constructor(init: {
    exit_code: number;
    signal: string | null;
  }) {
    Object.assign(this, init);
  }
/**
 * Returns `true` if the process exited normally with code `0`.
 */
  ok = defineInstanceFunction("baml.sys.ProcessExit.ok", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => boolean;
/**
 * Returns `true` if the process exited normally with code `0`.
 */
  ok_async = defineInstanceFunction("baml.sys.ProcessExit.ok", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<boolean>;
}

/**
 * A line-oriented view over a `ReadPipe`.
 * 
 * It reads through to the pipe on demand and holds only bytes past the last
 * newline. The final unterminated line is yielded at EOF. Invalid UTF-8 is
 * replaced with U+FFFD.
 */
export class ReadPipeLines {
  pipe!: ReadPipe;
  _pending!: Uint8Array;
  constructor(init: {
    pipe: ReadPipe;
    _pending: Uint8Array;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Drop one trailing carriage return so CRLF input produces clean lines.
 */
export const _strip_carriage_return = defineFunction("baml.sys._strip_carriage_return", "sync", ["line"]) as (line: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Uint8Array;

/**
 * Drop one trailing carriage return so CRLF input produces clean lines.
 */
export const _strip_carriage_return_async = defineFunction("baml.sys._strip_carriage_return", "async", ["line"]) as (line: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Uint8Array>;

/**
 * A live child process created with `start_process`.
 * 
 * `stdin` and `stdout` are always caller-owned pipes. `stderr` is populated
 * only when `ProcessOptions.stderr` is `StderrMode.Pipe`.
 */
export class Process {
  _handle!: _BamlHandle;
  stdin!: WritePipe;
  stdout!: ReadPipe;
  stderr!: ReadPipe | null;
  constructor(init: {
    _handle: _BamlHandle;
    stdin: WritePipe;
    stdout: ReadPipe;
    stderr: ReadPipe | null;
  }) {
    Object.assign(this, init);
  }
/**
 * Wait for the child to exit.
 * @throws Io
 * @throws Timeout
 */
  wait = defineInstanceFunction("baml.sys.Process.wait", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ProcessExit;
/**
 * Wait for the child to exit.
 * @throws Io
 * @throws Timeout
 */
  wait_async = defineInstanceFunction("baml.sys.Process.wait", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ProcessExit>;
/**
 * Request that the child terminate.
 * @throws Io
 */
  kill = defineInstanceFunction("baml.sys.Process.kill", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Request that the child terminate.
 * @throws Io
 */
  kill_async = defineInstanceFunction("baml.sys.Process.kill", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
/**
 * Terminate an un-waited child and close its stdin, stdout, and stderr pipes.
 * 
 * Safe to use with `defer { process.close() }`.
 */
  close = defineInstanceFunction("baml.sys.Process.close", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Terminate an un-waited child and close its stdin, stdout, and stderr pipes.
 * 
 * Safe to use with `defer { process.close() }`.
 */
  close_async = defineInstanceFunction("baml.sys.Process.close", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
}

/**
 * A system pipe for reading data, typically from another process.
 */
export class ReadPipe {
  _pipe!: _BamlHandle;
  constructor(init: {
    _pipe: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * Close the read pipe, releasing any resources.
 * @throws Io
 */
  close = defineInstanceFunction("baml.sys.ReadPipe.close", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Close the read pipe, releasing any resources.
 * @throws Io
 */
  close_async = defineInstanceFunction("baml.sys.ReadPipe.close", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
/**
 * Return a line-oriented view over this pipe.
 */
  lines = defineInstanceFunction("baml.sys.ReadPipe.lines", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ReadPipeLines;
/**
 * Return a line-oriented view over this pipe.
 */
  lines_async = defineInstanceFunction("baml.sys.ReadPipe.lines", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ReadPipeLines>;
}

/**
 * A system pipe for writing data, typically to another process.
 */
export class WritePipe {
  _pipe!: _BamlHandle;
  constructor(init: {
    _pipe: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * Close the write pipe, flushing pending data and delivering EOF.
 * @throws Io
 */
  close = defineInstanceFunction("baml.sys.WritePipe.close", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Close the write pipe, flushing pending data and delivering EOF.
 * @throws Io
 */
  close_async = defineInstanceFunction("baml.sys.WritePipe.close", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
}

/**
 * Runs `program` with the given `args` and returns its output. Throws on I/O failure or timeout.
 * @throws Io
 * @throws Timeout
 */
export const exec = defineFunction("baml.sys.exec", "sync", ["program", "args", "options"]) as (program: string, args: string[] | null, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ShellOutput;

/**
 * Runs `program` with the given `args` and returns its output. Throws on I/O failure or timeout.
 * @throws Io
 * @throws Timeout
 */
export const exec_async = defineFunction("baml.sys.exec", "async", ["program", "args", "options"]) as (program: string, args: string[] | null, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ShellOutput>;

/**
 * Starts `program` and returns a live process with caller-owned pipes.
 * 
 * Unlike `exec`, output is not buffered until process exit. Reading
 * `process.stdout` suspends only the current BAML green thread. If
 * `ProcessOptions.stdin` is set, this call writes that input and waits for the
 * child to consume it, bounded by `ProcessOptions.timeout_ms`.
 * @throws Io
 */
export const start_process = defineFunction("baml.sys.start_process", "sync", ["program", "args", "options"]) as (program: string, args: string[] | null, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Process;

/**
 * Starts `program` and returns a live process with caller-owned pipes.
 * 
 * Unlike `exec`, output is not buffered until process exit. Reading
 * `process.stdout` suspends only the current BAML green thread. If
 * `ProcessOptions.stdin` is set, this call writes that input and waits for the
 * child to consume it, bounded by `ProcessOptions.timeout_ms`.
 * @throws Io
 */
export const start_process_async = defineFunction("baml.sys.start_process", "async", ["program", "args", "options"]) as (program: string, args: string[] | null, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Process>;

/**
 * Runs a shell `command` string (passed to `/bin/sh -c`) and returns its output.
 * @throws Io
 * @throws Timeout
 */
export const shell = defineFunction("baml.sys.shell", "sync", ["command", "options"]) as (command: string, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ShellOutput;

/**
 * Runs a shell `command` string (passed to `/bin/sh -c`) and returns its output.
 * @throws Io
 * @throws Timeout
 */
export const shell_async = defineFunction("baml.sys.shell", "async", ["command", "options"]) as (command: string, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ShellOutput>;

/**
 * Suspends the current thread for `delay`.
 * @throws Io
 */
export const sleep = defineFunction("baml.sys.sleep", "sync", ["delay"]) as (delay: baml.time.Duration, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

/**
 * Suspends the current thread for `delay`.
 * @throws Io
 */
export const sleep_async = defineFunction("baml.sys.sleep", "async", ["delay"]) as (delay: baml.time.Duration, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;

/**
 * Forces a full garbage collection and runs queued `cleanup()` finalizers before returning.
 * Intended for deterministic tests and runtime diagnostics; production code should normally
 * let the runtime schedule collections automatically.
 */
export const collect_garbage = defineFunction("baml.sys.collect_garbage", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

/**
 * Forces a full garbage collection and runs queued `cleanup()` finalizers before returning.
 * Intended for deterministic tests and runtime diagnostics; production code should normally
 * let the runtime schedule collections automatically.
 */
export const collect_garbage_async = defineFunction("baml.sys.collect_garbage", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;

export const panic = defineFunction("baml.sys.panic", "sync", ["message"]) as (message: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => never;

export const panic_async = defineFunction("baml.sys.panic", "async", ["message"]) as (message: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<never>;

export const exit = defineFunction("baml.sys.exit", "sync", ["code"]) as (code: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => never;

export const exit_async = defineFunction("baml.sys.exit", "async", ["code"]) as (code: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<never>;

/**
 * Returns the command-line arguments passed to the BAML program, as an array of strings.
 */
export const argv = defineFunction("baml.sys.argv", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string[];

/**
 * Returns the command-line arguments passed to the BAML program, as an array of strings.
 */
export const argv_async = defineFunction("baml.sys.argv", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string[]>;

/**
 * Returns the process ID of the current process.
 * 
 * ## Panics
 * If the environment does not support process IDs (e.g. in a browser), with
 * `baml.panics.HostUnavailable`.
 */
export const pid = defineFunction("baml.sys.pid", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => number;

/**
 * Returns the process ID of the current process.
 * 
 * ## Panics
 * If the environment does not support process IDs (e.g. in a browser), with
 * `baml.panics.HostUnavailable`.
 */
export const pid_async = defineFunction("baml.sys.pid", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<number>;
