/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, initializeRuntimeFromBytecode, setTypeMap, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";
import * as _inlinedbaml from "./_inlinedbaml.js";
import { _TYPE_MAP } from "./_typemap.js";
import type * as ai from "./ai/index.js";
import type * as baml from "./baml/index.js";

initializeRuntimeFromBytecode(_inlinedbaml.BYTECODE, _inlinedbaml.BAML_TOML);
setTypeMap(_TYPE_MAP);

export * as ai from "./ai/index.js";
export * as baml from "./baml/index.js";
export * as reflect from "./reflect/index.js";
export * as vendor from "./vendor/index.js";

export class ToolPick$stream {
  matched!: boolean | null;
  tool!: string | null;
  args_json!: string | null;
  prompt_preview!: string | null;
  constructor(init: {
    matched: boolean | null;
    tool: string | null;
    args_json: string | null;
    prompt_preview: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const PickAction = defineFunction("user.PickAction", "sync", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const PickAction_async = defineFunction("user.PickAction", "async", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const PickAction$build_request = defineFunction("user.PickAction$build_request", "sync", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => baml.http.Request;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const PickAction$build_request_async = defineFunction("user.PickAction$build_request", "async", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * @throws LlmClient
 */
export const PickAction$parse = defineFunction("user.PickAction$parse", "sync", ["json"], undefined, { typeParams: ["T"] }) as <T>(json: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;

/**
 * @throws LlmClient
 */
export const PickAction$parse_async = defineFunction("user.PickAction$parse", "async", ["json"], undefined, { typeParams: ["T"] }) as <T>(json: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;

/**
 * @throws InvalidArgument
 * @throws CompilationError
 */
export const PickAction$render_prompt = defineFunction("user.PickAction$render_prompt", "sync", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => ai.Prompt;

/**
 * @throws InvalidArgument
 * @throws CompilationError
 */
export const PickAction$render_prompt_async = defineFunction("user.PickAction$render_prompt", "async", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<ai.Prompt>;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const PickAction$stream = defineFunction("user.PickAction$stream", "sync", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => ai.stream.Stream<T | null, T>;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const PickAction$stream_async = defineFunction("user.PickAction$stream", "async", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<ai.stream.Stream<T | null, T>>;

export class ToolPick {
  matched!: boolean;
  tool!: string;
  args_json!: string;
  prompt_preview!: string;
  constructor(init: {
    matched: boolean;
    tool: string;
    args_json: string;
    prompt_preview: string;
  }) {
    Object.assign(this, init);
  }
}

export const RouteAndDispatch = defineFunction("user.RouteAndDispatch", "sync", ["calculator_on", "unit_converter_on", "note_saver_on", "weather_on", "request", "mock_json"]) as (calculator_on: boolean, unit_converter_on: boolean, note_saver_on: boolean, weather_on: boolean, request: string, mock_json: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ToolPick;

export const RouteAndDispatch_async = defineFunction("user.RouteAndDispatch", "async", ["calculator_on", "unit_converter_on", "note_saver_on", "weather_on", "request", "mock_json"]) as (calculator_on: boolean, unit_converter_on: boolean, note_saver_on: boolean, weather_on: boolean, request: string, mock_json: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ToolPick>;
