/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, initializeRuntimeFromBytecode, setTypeMap, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";
import * as _inlinedbaml from "./_inlinedbaml.js";
import { _TYPE_MAP } from "./_typemap.js";
import type * as ai from "./ai/index.js";
import type * as baml from "./baml/index.js";

initializeRuntimeFromBytecode(_inlinedbaml.BYTECODE, _inlinedbaml.BAML_TOML);
setTypeMap(_TYPE_MAP);

export * as ai from "./ai/index.js";
export * as baml from "./baml/index.js";
export * as reflect from "./reflect/index.js";
export * as vendor from "./vendor/index.js";

export class ToolPick$stream {
  matched!: boolean | null;
  tool!: string | null;
  args_json!: string | null;
  prompt_preview!: string | null;
  constructor(init: {
    matched: boolean | null;
    tool: string | null;
    args_json: string | null;
    prompt_preview: string | null;
  }) {
    Object.assign(this, init);
  }
}

export type ToolId$stream = "calculator" | "unit_converter" | "note_saver" | "weather";

export type ToolId = "calculator" | "unit_converter" | "note_saver" | "weather";

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const pick_action = defineFunction("user.pick_action", "sync", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const pick_action_async = defineFunction("user.pick_action", "async", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const pick_action$build_request = defineFunction("user.pick_action$build_request", "sync", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => baml.http.Request;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const pick_action$build_request_async = defineFunction("user.pick_action$build_request", "async", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * @throws LlmClient
 */
export const pick_action$parse = defineFunction("user.pick_action$parse", "sync", ["json"], undefined, { typeParams: ["T"] }) as <T>(json: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;

/**
 * @throws LlmClient
 */
export const pick_action$parse_async = defineFunction("user.pick_action$parse", "async", ["json"], undefined, { typeParams: ["T"] }) as <T>(json: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;

/**
 * @throws InvalidArgument
 * @throws CompilationError
 */
export const pick_action$render_prompt = defineFunction("user.pick_action$render_prompt", "sync", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => ai.Prompt;

/**
 * @throws InvalidArgument
 * @throws CompilationError
 */
export const pick_action$render_prompt_async = defineFunction("user.pick_action$render_prompt", "async", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<ai.Prompt>;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const pick_action$stream = defineFunction("user.pick_action$stream", "sync", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => ai.stream.Stream<T | null, T>;

/**
 * @throws InvalidArgument
 * @throws Timeout
 * @throws UnknownError
 * @throws Cancelled
 * @throws CompilationError
 */
export const pick_action$stream_async = defineFunction("user.pick_action$stream", "async", ["request"], undefined, { typeParams: ["T"] }) as <T>(request: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<ai.stream.Stream<T | null, T>>;

export class ToolPick {
  matched!: boolean;
  tool!: string;
  args_json!: string;
  prompt_preview!: string;
  constructor(init: {
    matched: boolean;
    tool: string;
    args_json: string;
    prompt_preview: string;
  }) {
    Object.assign(this, init);
  }
}

export const route_and_dispatch = defineFunction("user.route_and_dispatch", "sync", ["enabled", "request"]) as (enabled: ToolId[], request: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ToolPick;

export const route_and_dispatch_async = defineFunction("user.route_and_dispatch", "async", ["enabled", "request"]) as (enabled: ToolId[], request: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ToolPick>;
