/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, type BamlCallContext, type BamlType } from "@boundaryml/baml-bridge";
import type * as reflect from "../../reflect/index.js";

/**
 * An enum-kind view of a `type` value. Users never construct this class.
 */
export class Type$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

export class Value {
  name!: string;
  meta!: reflect.Meta;
  constructor(init: {
    name: string;
    meta: reflect.Meta;
  }) {
    Object.assign(this, init);
  }
}

export class Value$stream {
  name!: string | null;
  meta!: reflect.Meta$stream | null;
  constructor(init: {
    name: string | null;
    meta: reflect.Meta$stream | null;
  }) {
    Object.assign(this, init);
  }
}

export const value = defineFunction("reflect.enum.value", "sync", ["name"], ["alias", "description", "docstring", "other"]) as (name: string, $opts?: { alias?: string | null | undefined; description?: string | null | undefined; docstring?: string | null | undefined; other?: { [key: string]: string } | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Value;

export const value_async = defineFunction("reflect.enum.value", "async", ["name"], ["alias", "description", "docstring", "other"]) as (name: string, $opts?: { alias?: string | null | undefined; description?: string | null | undefined; docstring?: string | null | undefined; other?: { [key: string]: string } | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Value>;

/**
 * @throws CompilationError
 */
const __baml_new = defineFunction("reflect.enum.new", "sync", ["name", "values"]) as (name: string, values: (string | Value)[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
export { __baml_new as new };

/**
 * @throws CompilationError
 */
export const new_async = defineFunction("reflect.enum.new", "async", ["name", "values"]) as (name: string, values: (string | Value)[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;

export const get_value = defineFunction("reflect.enum.get_value", "sync", ["value"]) as (value: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

export const get_value_async = defineFunction("reflect.enum.get_value", "async", ["value"]) as (value: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * An enum-kind view of a `type` value. Users never construct this class.
 */
export class Type {
  constructor(init: {}) {
    Object.assign(this, init);
  }
  values = defineInstanceFunction("reflect.enum.Type.values", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Value[];
  values_async = defineInstanceFunction("reflect.enum.Type.values", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Value[]>;
  meta = defineInstanceFunction("reflect.enum.Type.meta", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => reflect.Meta;
  meta_async = defineInstanceFunction("reflect.enum.Type.meta", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<reflect.Meta>;
}
