/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, type BamlCallContext } from "@boundaryml/baml-bridge";

/**
 * Whichever provider the user has a key for; OpenAI wins when both are set.
 * Lives in a namespace so the self-describing console (which enumerates the
 * root package's functions) doesn't grow a card for it.
 * @throws Io
 * @throws ParseError
 */
export const default_client = defineFunction("user.internal.default_client", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * Whichever provider the user has a key for; OpenAI wins when both are set.
 * Lives in a namespace so the self-describing console (which enumerates the
 * root package's functions) doesn't grow a card for it.
 * @throws Io
 * @throws ParseError
 */
export const default_client_async = defineFunction("user.internal.default_client", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
